[".nano"]
    type = "archive"
    url = "https://github.com/scopatz/nanorc/releases/download/2020.10.10/nanorc-2020.10.10.tar.gz"
    exact = true
    stripComponents = 1
[".password-store"]
    type = "git-repo"
    url = "https://github.com/StevenSermeus/password-store"
    branch = "master"
    refreshPeriod = "168h"

